import Sidebar from "@/app/_components/utils/sidebar/sidebar";
import type { Metadata } from "next";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
  title: "SastaGram-Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='flex gap-1'>
      <Sidebar />
      <Separator orientation='vertical' className='bg-[#29151e]' />
      <div className='flex flex-[85]'>{children}</div>
    </main>
  );
}
